import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/Header";
import { dark, neobrutalism } from "@clerk/themes";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider appearance={{
         baseTheme: [neobrutalism, dark]
        }}>
          <Header/>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
